def error(e: Exception) -> print:
    """Error utility. Prints the associated exception."""
    print(f"There was a problem executing the program: {e}")
